[package]
name = "cli"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "aegis"
path = "src/main.rs"

[dependencies]
aegis-core = { path = "../core" }
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
colored.workspace = true
reqwest.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
